/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rupeng_gtk4j_GTK */

#ifndef _Included_com_rupeng_gtk4j_GTK
#define _Included_com_rupeng_gtk4j_GTK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    g_signal_connect
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_g_1signal_1connect
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    findConst
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_findConst
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1main
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_main_quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1main_1quit
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_new
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1new
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_show
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1show
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_hide
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1hide
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_set_can_focus
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1set_1can_1focus
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_get_can_focus
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1get_1can_1focus
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_has_focus
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1has_1focus
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_grab_focus
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1grab_1focus
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_set_visible
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1set_1visible
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_get_visible
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1get_1visible
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_set_sensitive
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1set_1sensitive
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_get_sensitive
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1get_1sensitive
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_get_parent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1get_1parent
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_set_parent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1set_1parent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_get_toplevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1get_1toplevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_is_toplevel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1is_1toplevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_set_app_paintable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1set_1app_1paintable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_get_screen
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1get_1screen
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_has_screen
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1has_1screen
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_screen_get_width
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1screen_1get_1width
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_screen_get_height
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1screen_1get_1height
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_screen_get_default
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1screen_1get_1default
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_screen_get_n_monitors
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1screen_1get_1n_1monitors
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_screen_get_primary_monitor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1screen_1get_1primary_1monitor
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_screen_get_monitor_workarea
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1screen_1get_1monitor_1workarea
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_set_size_request
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1set_1size_1request
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_set_title
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1set_1title
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_get_title
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1get_1title
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_set_resizable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1set_1resizable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_get_resizable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1get_1resizable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_set_modal
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1set_1modal
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_set_default_size
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1set_1default_1size
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_set_position
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1set_1position
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_fullscreen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1fullscreen
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_unfullscreen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1unfullscreen
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_window_maximize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1window_1maximize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_fixed_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1fixed_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_fixed_put
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1fixed_1put
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_container_add
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1container_1add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_container_remove
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1container_1remove
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_container_get_children
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1container_1get_1children
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_label_new
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1label_1new
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_label_set_text
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1label_1set_1text
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_label_get_text
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1label_1get_1text
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_button_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1button_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_button_new_with_label
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1button_1new_1with_1label
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_button_set_label
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1button_1set_1label
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_button_get_label
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1button_1get_1label
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_button_set_image
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1button_1set_1image
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_button_set_image_position
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1button_1set_1image_1position
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_calendar_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1calendar_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_calendar_select_month
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1calendar_1select_1month
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_calendar_select_day
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1calendar_1select_1day
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_calendar_get_year
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1calendar_1get_1year
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_calendar_get_month
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1calendar_1get_1month
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_calendar_get_day
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1calendar_1get_1day
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_box_new
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1box_1new
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_box_pack_start
 * Signature: (IIZZI)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1box_1pack_1start
  (JNIEnv *, jclass, jint, jint, jboolean, jboolean, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_box_pack_end
 * Signature: (IIZZI)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1box_1pack_1end
  (JNIEnv *, jclass, jint, jint, jboolean, jboolean, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_box_set_homogeneous
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1box_1set_1homogeneous
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_grid_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1grid_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_grid_insert_row
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1grid_1insert_1row
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_grid_insert_column
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1grid_1insert_1column
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_grid_attach
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1grid_1attach
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_grid_set_row_spacing
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1grid_1set_1row_1spacing
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_grid_set_column_spacing
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1grid_1set_1column_1spacing
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_grid_set_row_homogeneous
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1grid_1set_1row_1homogeneous
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_grid_set_column_homogeneous
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1grid_1set_1column_1homogeneous
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_message_dialog_new
 * Signature: (IIIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1message_1dialog_1new
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_dialog_run
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1dialog_1run
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_dialog_response
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1dialog_1response
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_dialog_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1dialog_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_dialog_new_with_buttons
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1dialog_1new_1with_1buttons
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_dialog_get_action_area
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1dialog_1get_1action_1area
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_dialog_get_content_area
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1dialog_1get_1content_1area
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_dialog_add_button
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1dialog_1add_1button
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_toggle_button_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1toggle_1button_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_toggle_button_new_with_label
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1toggle_1button_1new_1with_1label
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_toggle_button_new_with_mnemonic
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1toggle_1button_1new_1with_1mnemonic
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_toggle_button_set_active
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1toggle_1button_1set_1active
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_toggle_button_get_active
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1toggle_1button_1get_1active
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_check_button_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1check_1button_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_check_button_new_with_label
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1check_1button_1new_1with_1label
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_check_button_new_with_mnemonic
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1check_1button_1new_1with_1mnemonic
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_get_active
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1get_1active
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_set_active
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1set_1active
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_get_active_id
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1get_1active_1id
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_set_active_id
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1set_1active_1id
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_text_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1text_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_text_append_text
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1text_1append_1text
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_text_remove
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1text_1remove
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_text_get_active_text
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1text_1get_1active_1text
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_text_remove_all
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1text_1remove_1all
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_combo_box_text_append
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1combo_1box_1text_1append
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_entry_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1entry_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_entry_set_max_length
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1entry_1set_1max_1length
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_entry_get_max_length
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1entry_1get_1max_1length
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_entry_get_text_length
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1entry_1get_1text_1length
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_entry_set_text
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1entry_1set_1text
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_entry_get_text
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1entry_1get_1text
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_entry_set_invisible_char
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1entry_1set_1invisible_1char
  (JNIEnv *, jclass, jint, jchar);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_entry_set_visibility
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1entry_1set_1visibility
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_select_region
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1select_1region
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_insert_text
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1insert_1text
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_delete_text
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1delete_1text
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_cut_clipboard
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1cut_1clipboard
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_copy_clipboard
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1copy_1clipboard
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_paste_clipboard
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1paste_1clipboard
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_delete_selection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1delete_1selection
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_set_position
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1set_1position
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_get_position
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1get_1position
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_set_editable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1set_1editable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_editable_get_editable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1editable_1get_1editable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_spin_button_new_with_range
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1spin_1button_1new_1with_1range
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_spin_button_get_value
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1spin_1button_1get_1value
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_spin_button_get_value_as_int
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1spin_1button_1get_1value_1as_1int
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_spin_button_set_value
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1spin_1button_1set_1value
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_spin_button_set_digits
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1spin_1button_1set_1digits
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_image_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1image_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_image_new_from_file
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1image_1new_1from_1file
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_image_new_from_stock
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1image_1new_1from_1stock
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_image_clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1image_1clear
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_image_set_from_stock
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1image_1set_1from_1stock
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_image_set_from_file
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1image_1set_1from_1file
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_radio_button_new
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1radio_1button_1new
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_radio_button_new_with_label
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1radio_1button_1new_1with_1label
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_radio_button_new_with_label_from_widget
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1radio_1button_1new_1with_1label_1from_1widget
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_range_set_value
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1range_1set_1value
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_range_get_value
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1range_1get_1value
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_scale_new_with_range
 * Signature: (IDDD)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1scale_1new_1with_1range
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_scale_get_draw_value
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1scale_1get_1draw_1value
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_scale_set_draw_value
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1scale_1set_1draw_1value
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_scrolled_window_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1scrolled_1window_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_scrolled_window_add_with_viewport
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1scrolled_1window_1add_1with_1viewport
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_progress_bar_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1progress_1bar_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_progress_bar_set_fraction
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1progress_1bar_1set_1fraction
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_progress_bar_get_fraction
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1progress_1bar_1get_1fraction
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_progress_bar_set_text
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1progress_1bar_1set_1text
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_progress_bar_get_text
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1progress_1bar_1get_1text
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_progress_bar_set_show_text
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1progress_1bar_1set_1show_1text
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_progress_bar_get_show_text
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1progress_1bar_1get_1show_1text
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_notebook_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1notebook_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_notebook_append_page
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1notebook_1append_1page
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_notebook_set_tab_pos
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1notebook_1set_1tab_1pos
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_bar_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1bar_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_item_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1item_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_item_new_with_label
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1item_1new_1with_1label
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_item_new_with_mnemonic
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1item_1new_1with_1mnemonic
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_item_set_submenu
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1item_1set_1submenu
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_shell_append
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1shell_1append
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_attach_to_widget
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1attach_1to_1widget
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_popup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1popup
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_override_background_color
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1override_1background_1color
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_override_color
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1override_1color
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_iter_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1iter_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_iter_free
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1iter_1free
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_model_get_iter_first
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1model_1get_1iter_1first
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_model_iter_previous
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1model_1iter_1previous
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_model_iter_next
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1model_1iter_1next
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_model_get_value
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1model_1get_1value
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_list_store_iter_is_valid
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1list_1store_1iter_1is_1valid
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_list_store_new
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1list_1store_1new
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_list_store_append
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1list_1store_1append
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_list_store_set_value
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1list_1store_1set_1value
  (JNIEnv *, jclass, jint, jint, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_list_store_clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1list_1store_1clear
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_store_new
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1store_1new
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_store_append
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1store_1append
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_store_set_value
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1store_1set_1value
  (JNIEnv *, jclass, jint, jint, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_store_clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1store_1clear
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_cell_renderer_text_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1cell_1renderer_1text_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_column_new_with_attributes
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1column_1new_1with_1attributes
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_column_set_visible
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1column_1set_1visible
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_column_get_visible
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1column_1get_1visible
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_column_set_resizable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1column_1set_1resizable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_column_get_resizable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1column_1get_1resizable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_column_set_reorderable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1column_1set_1reorderable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_column_get_reorderable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1column_1get_1reorderable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_column_set_sort_column_id
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1column_1set_1sort_1column_1id
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_append_column
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1append_1column
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_remove_column
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1remove_1column
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_get_n_columns
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1get_1n_1columns
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_get_column
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1get_1column
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_set_model
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1set_1model
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_get_headers_visible
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1get_1headers_1visible
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_set_headers_visible
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1set_1headers_1visible
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_get_selection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1get_1selection
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_selection_set_mode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1selection_1set_1mode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_selection_get_mode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1selection_1get_1mode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tree_view_get_selection_indices
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tree_1view_1get_1selection_1indices
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_chooser_dialog_new
 * Signature: (Ljava/lang/String;IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1chooser_1dialog_1new
  (JNIEnv *, jclass, jstring, jint, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_chooser_set_select_multiple
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1chooser_1set_1select_1multiple
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_chooser_set_current_name
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1chooser_1set_1current_1name
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_chooser_get_filename
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1chooser_1get_1filename
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_chooser_get_filenames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1chooser_1get_1filenames
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_chooser_set_do_overwrite_confirmation
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1chooser_1set_1do_1overwrite_1confirmation
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_chooser_set_create_folders
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1chooser_1set_1create_1folders
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_filter_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1filter_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_filter_set_name
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1filter_1set_1name
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_filter_add_pattern
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1filter_1add_1pattern
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_file_chooser_add_filter
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1file_1chooser_1add_1filter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_switch_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1switch_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_switch_set_active
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1switch_1set_1active
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_switch_get_active
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1switch_1get_1active
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_iter_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1iter_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_iter_free
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1iter_1free
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_iter_forward_to_end
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1iter_1forward_1to_1end
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_iter_get_line
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1iter_1get_1line
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_iter_forward_char
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1iter_1forward_1char
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_iter_backward_char
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1iter_1backward_1char
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_view_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1view_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_view_get_buffer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1view_1get_1buffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_buffer_get_text
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1buffer_1get_1text
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_buffer_set_text
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1buffer_1set_1text
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_buffer_insert
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1buffer_1insert
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_buffer_get_iter_at_line_index
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1buffer_1get_1iter_1at_1line_1index
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_buffer_get_iter_at_offset
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1buffer_1get_1iter_1at_1offset
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_buffer_get_iter_at_line
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1buffer_1get_1iter_1at_1line
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_buffer_get_start_iter
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1buffer_1get_1start_1iter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_buffer_get_end_iter
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1buffer_1get_1end_1iter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_view_set_wrap_mode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1view_1set_1wrap_1mode
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_view_get_wrap_mode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1view_1get_1wrap_1mode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_view_set_editable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1view_1set_1editable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_text_view_get_editable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1text_1view_1get_1editable
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    mci_open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_mci_1open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    mci_play
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_mci_1play
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    mci_close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_mci_1close
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    mci_pause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_mci_1pause
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    mci_seek
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_mci_1seek
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    mci_get_status
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_rupeng_gtk4j_GTK_mci_1get_1status
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    _g_timeout_add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK__1g_1timeout_1add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    _g_idle_add
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK__1g_1idle_1add
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_event_get_state
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1event_1get_1state
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_event_get_coords_x
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1event_1get_1coords_1x
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_event_get_coords_y
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1event_1get_1coords_1y
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_event_get_type
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1event_1get_1type
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_event_get_keyval
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1event_1get_1keyval
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_event_get_keycode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1event_1get_1keycode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gdk_event_get_button
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gdk_1event_1get_1button
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_toolbar_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1toolbar_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_toolbar_insert
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1toolbar_1insert
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tool_item_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tool_1item_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tool_item_set_tooltip_text
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tool_1item_1set_1tooltip_1text
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tool_button_new
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tool_1button_1new
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tool_button_set_label
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tool_1button_1set_1label
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tool_button_set_stock_id
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tool_1button_1set_1stock_1id
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_tool_button_set_icon_widget
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1tool_1button_1set_1icon_1widget
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_tool_button_new
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1tool_1button_1new
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_tool_button_new_from_stock
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1tool_1button_1new_1from_1stock
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_menu_tool_button_set_menu
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1menu_1tool_1button_1set_1menu
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_event_box_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1event_1box_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_add_events
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1add_1events
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_draw
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1draw
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_queue_draw
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1queue_1draw
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_get_allocated_width
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1get_1allocated_1width
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_widget_get_allocated_height
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1widget_1get_1allocated_1height
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_status_icon_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1status_1icon_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_status_icon_set_from_file
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1status_1icon_1set_1from_1file
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_status_icon_set_from_stock
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1status_1icon_1set_1from_1stock
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_status_icon_set_tooltip_text
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1status_1icon_1set_1tooltip_1text
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_status_icon_set_visible
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1status_1icon_1set_1visible
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_status_icon_get_visible
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1status_1icon_1get_1visible
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    g_error
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_rupeng_gtk4j_GTK_g_1error
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_rupeng_gtk4j_GTK
 * Method:    gtk_drawing_area_new
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_rupeng_gtk4j_GTK_gtk_1drawing_1area_1new
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
